<?php

// SET VARIABLE.
$someVar = "Some content";

// IMPORTANT: 123 STEPS.
$anotherVar = 123;

// Fetch data.
$data = fetch();

// if ( false === \as_has_scheduled_action( 'update_action' ) ) {
//   \as_schedule_recurring_action( strtotime( 'now' ), DAY_IN_SECONDS, 'update_action', [], '', true );
// }

// RETURNS ONE VALUE.
function test_one() {
}

// CLASS ONE.
class Test_One{
	// VAR TEST.
	protects var $test_var;

	// RETURNS ONE VALUE.
	public function test_one() {
	}
}
